#%RAML 1.0
title: OpenWarming API
version: v1
baseUri: http://localhost:8888
mediaType:  application/json

types: 
  OpenWarmingResponse:
    properties: 
          repositoriesCount: number
          avgTemperatures: number[]
    description: |
        Contains the number of repositories created by the user,
        and a list of the average temperatures of each day of creation.
    ErrorMessage:
        properties:
            message: string
        description: |
            Error message description.

# TODO: Add response examples

/temperatures:
    /{githubUser}:
        get:
            responses:
                200:
                    body:
                        application/json:
                            type: OpenWarmingResponse
                404:
                    body:
                        application/json:
                            type: ErrorMessage
                    description: |
                        Invalid username or username has no location.
                        Also shown in returned message.
                500:
                    body:
                        application/json:
                            type: ErrorMessage
                    description: |
                        Internal sever error. Check server CLI output, or error stacktrace.

